spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    hikari:
      username: root
      password: 123456
      # >= 6.x: com.mysql.cj.jdbc.Driver
      # <= 5.x: com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
        #指定namespace
        namespace: 76cf2c29-211c-4d74-9991-592fd0be4c89
        # NJ
        # 指定集群名称
        cluster-name: BJ
        metadata:
          instance: c
          haha: hehe
          version: v1
  application:
    # ???????-????_????????
    name: user-center